### ISSUE TITLE
LORA Questions

### ISSUE THREAD

**Issue by garudaonekh** [arijav/AriloSprinkler-Firmware#24]
Hi,
Have you integrated LORA into your system? I need use it for long distance farm irrigation around 500 to 1km apart.
Please let me know the LORA that's compatible with your code as I have seen many model and I am not very familiar with their compatibility.

I plan to do like this

1. LORA in the Main Controller

2. ESP32+LORA for each group of 8 stations.

Is this something your code can achieve without any code update?
If you have a better suggestion, please share me.

Thanks;

**Comment by arijav** [comment]
Hi, yes I have integrated a module (E22-900M30S-SX1262) in the SW/HW and it is working nicely. You can perform long distance irrigation with it. I do not see any need to change the code for your application. Please have a look to the readme, everything is explained there.

BR,

Javier
